SECRET_KEY = 'ckanlkvunekvunae3485vnksaj34t93@GH5OIJLghOIJ($*tu_43T8HIAGK4UWEGH#f*hIUEFUFHIW@l(r*yUEHVIKUehki'
COINBASE_API_KEY = 'dflsjO2v2UQ0vDox'
COINBASE_SECRET_API_KEY = 'YjG1VNHdoqZZPjqp2xBw9FBknEUPxEv1'